---
#
# Ansible managed
#
repository:
  description: Install and configure Memcached for Linux
  homepage: https://buluma.github.io/
  topics: web, database, memcached, keyvalue, kv, cache, caching, performance, ansible, molecule, tox, playbook
