---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if memcached is running
      ansible.builtin.service_facts:

    - name: Assert memcached is active
      ansible.builtin.assert:
        that:
          - "'memcached.service' in services"
          - "services['memcached.service']['state'] == 'running'"
        quiet: true
